import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'

test('peg window keeps only a blue frame plus the image content', () => {
  const html = fs.readFileSync(path.resolve('public/peg-window.html'), 'utf8')

  assert.match(html, /#root\s*\{/)
  assert.match(html, /--peg-frame-width:\s*6px;/)
  assert.match(html, /position:\s*relative;/)
  assert.match(html, /tabindex="0"/)
  assert.match(html, /padding:\s*var\(--peg-frame-width\);/)
  assert.match(html, /box-sizing:\s*border-box;/)
  assert.match(html, /background:\s*rgba\(123,\s*200,\s*255,\s*0\.52\);/)
  assert.match(html, /border-radius:\s*10px;/)
  assert.match(html, /overflow:\s*hidden;/)
  assert.match(html, /#root:focus,/)
  assert.match(html, /#root:focus-visible/)
  assert.match(html, /outline:\s*none;/)
  assert.match(html, /background:\s*rgb\(123,\s*200,\s*255\);/)
  assert.match(html, /background:\s*transparent;/)
  assert.match(html, /#frame\s*\{/)
  assert.match(html, /position:\s*relative;/)
  assert.match(html, /overflow:\s*hidden;/)
  assert.match(html, /border-radius:\s*calc\(10px - var\(--peg-frame-width\)\);/)
  assert.match(html, /#image\s*\{/)
  assert.match(html, /\.peg-attention\s*\{/)
  assert.match(html, /animation:\s*peg-attention 780ms/)
  assert.match(html, /#root\.peg-copied\s*\{/)
  assert.match(html, /@keyframes peg-copied-border/)
  assert.match(html, /@keyframes peg-copied-text/)
  assert.match(html, /#copy-feedback\s*\{/)
  assert.match(html, /已复制/)
  assert.match(html, /#root\.peg-copied #copy-feedback/)
  assert.match(html, /animation:\s*peg-copied-text 720ms/)
  assert.match(html, /@keyframes peg-attention/)
  assert.match(html, /root\.addEventListener\(\s*'wheel'/)
  assert.match(html, /window\.addEventListener\('gesturestart'/)
  assert.match(html, /window\.addEventListener\('gesturechange'/)
  assert.match(html, /window\.addEventListener\('gestureend'/)
  assert.match(html, /window\.addEventListener\('keydown'/)
  assert.match(html, /window\.addEventListener\('copy'/)
  assert.match(html, /function shouldHandleEscapeClose/)
  assert.match(html, /function handlePegCloseRequest/)
  assert.match(html, /event\.key === 'Escape'/)
  assert.match(html, /sendToParent\(\{ type: 'close' }\)/)
  assert.match(html, /const WHEEL_ZOOM_END_DELAY_MS = 80/)
  assert.match(html, /const MAX_LIVE_ZOOM_LOG_STEP = 0\.032/)
  assert.match(html, /const MIN_LIVE_ZOOM_LOG_STEP = 0\.0045/)
  assert.match(html, /const ZOOM_SMOOTHING_RATIO = 0\.72/)
  assert.match(html, /event\.deltaMode/)
  assert.match(html, /function clampLiveScaleFactor/)
  assert.match(html, /function cancelQueuedZoom/)
  assert.match(html, /function focusPegSurface/)
  assert.match(html, /function playCopyFeedback/)
  assert.match(html, /function copyPeggedImageToClipboard/)
  assert.match(html, /function shouldHandleCopyShortcut/)
  assert.match(html, /function handleClipboardCopyRequest/)
  assert.match(html, /function dispatchImmediateZoomFrame/)
  assert.match(html, /window\.utools\.copyImage/)
  assert.match(html, /event\.code === 'KeyC'/)
  assert.match(html, /lastClipboardWriteAt/)
  assert.match(html, /const PEG_COPIED_CLASS = 'peg-copied'/)
  assert.match(html, /const PEG_COPIED_DURATION_MS = 720/)
  assert.match(html, /root\?\.focus\?\.\(\{ preventScroll: true \}\)/)
  assert.match(html, /clipboardImageSource = sourceImage/)
  assert.match(html, /pendingZoomLogDelta/)
  assert.match(html, /zoomEndRequested/)
  assert.match(html, /Math\.log\(clampLiveScaleFactor/)
  assert.match(html, /window\.cancelAnimationFrame/)
  assert.match(html, /requestAnimationFrame/)
  assert.match(html, /window\.__SCREEN_TRANSLATION_PEG_ATTENTION__/)
  assert.match(html, /const EDGE_WHITE_THRESHOLD = 234/)
  assert.match(html, /const CONTENT_BOUNDS_PADDING = 0/)
  assert.match(html, /function removeEdgeNearWhitePixels/)
  assert.match(html, /function findVisibleContentBounds/)
  assert.match(html, /function scaleContentBoundsToTarget/)
  assert.match(html, /createProcessedImageDataUrl/)
  assert.match(html, /const cleanedPixels = removeEdgeNearWhitePixels/)
  assert.match(html, /data:\s*cleanedPixels/)
  assert.match(html, /cropContext\.drawImage\(\s*probe,/)
  assert.match(html, /resolve\(source\)/)
  assert.match(html, /--peg-frame-width/)
  assert.match(html, /frameInset/)
  assert.doesNotMatch(html, /filter:\s*drop-shadow\(/)
  assert.doesNotMatch(html, /require\('\.\/preload\/pegImageMask\.cjs'\)/)
})
