import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'

test('pin window keeps a transparent outer border outside the image content', () => {
  const html = fs.readFileSync(path.resolve('public/pin-window.html'), 'utf8')

  assert.match(html, /#root\s*\{/)
  assert.match(html, /--pin-shadow-gap:\s*6px;/)
  assert.match(html, /position:\s*relative;/)
  assert.match(html, /tabindex="0"/)
  assert.match(html, /padding:\s*var\(--pin-shadow-gap\);/)
  assert.match(html, /background:\s*transparent;/)
  assert.match(html, /#root::after\s*\{/)
  assert.match(html, /border-radius:\s*10px;/)
  assert.match(html, /border:\s*6px solid rgba\(123,\s*200,\s*255,\s*0\.52\);/)
  assert.match(html, /box-sizing:\s*border-box;/)
  assert.match(html, /pointer-events:\s*none;/)
  assert.match(html, /#frame\s*\{/)
  assert.match(html, /overflow:\s*hidden;/)
  assert.match(html, /border-radius:\s*8px;/)
  assert.match(html, /#image\s*\{/)
  assert.match(html, /\.pin-attention\s*\{/)
  assert.match(html, /animation:\s*pin-attention 780ms/)
  assert.match(html, /#root\.pin-copied::after/)
  assert.match(html, /@keyframes pin-copied-border/)
  assert.match(html, /@keyframes pin-copied-text/)
  assert.match(html, /#copy-feedback\s*\{/)
  assert.match(html, /已复制/)
  assert.match(html, /#root\.pin-copied #copy-feedback/)
  assert.match(html, /animation:\s*pin-copied-text 720ms/)
  assert.match(html, /@keyframes pin-attention/)
  assert.match(html, /root\.addEventListener\(\s*'wheel'/)
  assert.match(html, /window\.addEventListener\('gesturestart'/)
  assert.match(html, /window\.addEventListener\('gesturechange'/)
  assert.match(html, /window\.addEventListener\('gestureend'/)
  assert.match(html, /window\.addEventListener\('keydown'/)
  assert.match(html, /window\.addEventListener\('copy'/)
  assert.match(html, /function shouldHandleEscapeClose/)
  assert.match(html, /function handlePinCloseRequest/)
  assert.match(html, /event\.key === 'Escape'/)
  assert.match(html, /sendToParent\(\{ type: 'close' }\)/)
  assert.match(html, /const WHEEL_ZOOM_END_DELAY_MS = 80/)
  assert.match(html, /const MAX_LIVE_ZOOM_LOG_STEP = 0\.032/)
  assert.match(html, /const MIN_LIVE_ZOOM_LOG_STEP = 0\.0045/)
  assert.match(html, /const ZOOM_SMOOTHING_RATIO = 0\.72/)
  assert.match(html, /event\.deltaMode/)
  assert.match(html, /function clampLiveScaleFactor/)
  assert.match(html, /function cancelQueuedZoom/)
  assert.match(html, /function focusPinSurface/)
  assert.match(html, /function playCopyFeedback/)
  assert.match(html, /function copyPinnedImageToClipboard/)
  assert.match(html, /function shouldHandleCopyShortcut/)
  assert.match(html, /function handleClipboardCopyRequest/)
  assert.match(html, /function dispatchImmediateZoomFrame/)
  assert.match(html, /window\.utools\.copyImage/)
  assert.match(html, /event\.code === 'KeyC'/)
  assert.match(html, /lastClipboardWriteAt/)
  assert.match(html, /const PIN_COPIED_CLASS = 'pin-copied'/)
  assert.match(html, /const PIN_COPIED_DURATION_MS = 720/)
  assert.match(html, /root\?\.focus\?\.\(\{ preventScroll: true \}\)/)
  assert.match(html, /clipboardImageSource = sourceImage/)
  assert.match(html, /pendingZoomLogDelta/)
  assert.match(html, /zoomEndRequested/)
  assert.match(html, /Math\.log\(clampLiveScaleFactor/)
  assert.match(html, /window\.cancelAnimationFrame/)
  assert.match(html, /requestAnimationFrame/)
  assert.match(html, /window\.__SCREEN_TRANSLATION_PIN_ATTENTION__/)
  assert.match(html, /const EDGE_WHITE_THRESHOLD = 234/)
  assert.match(html, /function removeEdgeNearWhitePixels/)
  assert.match(html, /function findVisibleContentBounds/)
  assert.match(html, /function scaleContentBoundsToTarget/)
  assert.match(html, /createProcessedImageDataUrl/)
  assert.doesNotMatch(html, /filter:\s*drop-shadow\(/)
  assert.doesNotMatch(html, /require\('\.\/preload\/pinImageMask\.cjs'\)/)
})
